### ISSUE TITLE
Which Python version is preferred for this?

### ISSUE THREAD

**Issue by guanwang19** [BurhanUlTayyab/GPTZero#6]

**Comment by BurhanUlTayyab** [comment]
We have used Python3.8 but any Python3 will make it.

**Comment by guanwang19** [comment]
thank you!my computers mac and pc don't have nvidia gpu, hoe can make it run?
Very respectfully,
Guan Wang 

    On Friday, February 10, 2023 at 09:05:07 PM EST, Burhan Ul Tayyab ***@***.***> wrote:  
 
 


We have used Python3.8 but any Python3 will make it.

**Comment by BurhanUlTayyab** [comment]
Yes, you have to initialize the model like this to run on CPU

model = GPT2PPL(device=“cpu”)

**Comment by guanwang19** [comment]
Thanks again，
 I tried. Still I got error saying torch not compiled with cuda enabled.
